### ISSUE TITLE
not_found_error

### ISSUE THREAD

**Issue by TheFireRed** [inertia42/omegat-openaitrans-plugin#3]
I'm using https://api.anthropic.com/v1/messages as URL and the MT windows shows the following:

error: {"type":"not_found_error","message":"Not Found"}

If I try to use https://api.anthropic.com/ instead, the error says:

error: {"type":"invalid_request_error","message":"anthropic-version: header is required"}

Any help?

**Comment by inertia42** [comment]
This bug may have been caused by not properly adapting to the official API request format provided by Claude earlier. I've attempted to fix it in version v1.2.1. However, since I don't currently have an official Claude API, I can't actually test this modification. You can try the latest changes to see if they work.

Furthermore, the URL should be similar to https://api.anthropic.com (without slash /), as shown in the example provided in the configuration interface.

**Comment by TheFireRed** [comment]
I'll be more than happy to test! However, I think the .jar file is missing from the 1.2.1 release.

EDIT: I see it now, that was quick 🤗 thanks a lot!

**Comment by inertia42** [comment]
> I'll be more than happy to test! However, I think the .jar file is missing from the 1.2.1 release.

Oh sorry, I forgot to upload the jar file.

**Comment by TheFireRed** [comment]
It *does* work if I select claude-3-5-sonnet-20240620, but other models reply with
`error: {"type":"not_found_error","message":"model: claude-3-5-sonnet"}`

(merely commenting for future-proofing when new models or updates appear).

Thanks a lot!

**Comment by inertia42** [comment]
> It _does_ work if I select claude-3-5-sonnet-20240620, but other models reply with `error: {"type":"not_found_error","message":"model: claude-3-5-sonnet"}`
> 
> (merely commenting for future-proofing when new models or updates appear).
> 
> Thanks a lot!

Thank you for your feedback. I'm currently using a third-party API service, not the official Claude API. Therefore, I'm unable to test the issue you mentioned at the moment. If I can obtain the official Claude API in the future, I will conduct further tests on this matter.

**Comment by TheFireRed** [comment]
If it helps, there's a free $5 credit for first-time user registrations, valid for two weeks and with some other limitations, that won't charge your card. Other than that, it helps you set you on your feet. However, now that I'm reading Anthropic's documentation, it seems it doesn't offer commercial API access to China. I can help you get this free API credit if there's a way of safely/privately relaying the API key to you. 😊

**Comment by inertia42** [comment]
> If it helps, there's a free $5 credit for first-time user registrations, valid for two weeks and with some other limitations, that won't charge your card. Other than that, it helps you set you on your feet. However, now that I'm reading Anthropic's documentation, it seems it doesn't offer commercial API access to China. I can help you get this free API credit if there's a way of safely/privately relaying the API key to you. 😊

Oh, thank you so much for your help🤗. If you could provide an API for testing, I should be able to quickly fix the related issues.

**Comment by inertia42** [comment]
Fixed.
